projectBuilding:

  plainCopying:

    filesGroups:
            
      Primer:
        sourceFileRelativePath: node_modules/@yamato-daiwa/frontend-demos/Distributions/YDF-Demos-Primer.css
        buildingModeDependent:
          PRODUCTION: { outputDirectoryRelativePath: wwwroot/css }
          
          
      CommonRequirements:
        sourceFileRelativePath: node_modules/@yamato-daiwa/frontend-demos/Distributions/YDF-Demos-CommonRequirements.css
        buildingModeDependent:
          PRODUCTION: { outputDirectoryRelativePath: wwwroot/css }
 