projectBuilding:

  ECMA_ScriptLogicProcessing:

    entryPointsGroups:

      Logic:

        singleEntryPointSourceFileRelativePath: YDF.ts

        targetRuntime:
          type: BROWSER

        distributing:
          exposingOfExportsFromEntryPoints:
            mustExpose: true

        buildingModeDependent:

          PRODUCTION:
            outputTopDirectoryRelativePath: ""
            revisioning: { disable: true }
