extends: ./node_modules/@yamato-daiwa/style_guides/ECMAScript.js

rules:

  # The dependencies are either bundled by Webpack of peer
  "node/no-unpublished-import": off


overrides:

  - files: [ "Source/SVG_Icons/**/*.vue" ]
    rules:

      # The imports from Pug could be long but could not be split
      "@stylistic/max-len": off

      # The import from the Pug must not be counted as element
      "vue/valid-template-root": off
