extends: ./node_modules/@yamato-daiwa/style_guides/ECMAScript.js


overrides:


- files: [ "Source/**/**GalleryPage.ts" ]
  rules:

    # 【 応用理由 】 「data」と言う変数名は禁じられてはいるが、オブジェクトのプロパティ名は記事られていない。
    # 然し、コミュニティは選択的に禁じる機能を導入を拒否した。
    # https://github.com/eslint/eslint/issues/15504
    "id-denylist": off
