projectBuilding:

  commonSettings:

    selectiveExecutions:

      Distributable:

        tasksAndSourceFilesSelection:

          ECMA_ScriptLogicProcessing: [ Distributable ]

      Workbenches:

        tasksAndSourceFilesSelection:

          markupProcessing: [ Workbenches ]
          stylesProcessing: [ Workbenches ]
          ECMA_ScriptLogicProcessing: [ Workbenches ]

        browserLiveReloadingSetupID: Workbenches


  # ━━━ Markup ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
  markupProcessing:

    common:
      buildingModeDependent:
        LOCAL_DEVELOPMENT: { mustResolveResourceReferencesToRelativePaths: true }

    entryPointsGroups:

      Workbenches:

        sourceFilesTopDirectoryRelativePath: Workbenches/Source
        partialsRecognition:
          excludeFilesWithPrefixes: "_"
          excludeSubdirectoriesWithPrefixes: "_"

        buildingModeDependent:
          LOCAL_DEVELOPMENT:
            outputTopDirectoryRelativePath: Workbenches/Output


  # ━━━ Styles ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
  stylesProcessing:

    entryPointsGroups:

      Workbenches:

        sourceFilesTopDirectoryRelativePath: Workbenches/Source

        partialsRecognition:
          excludeFilesWithPrefixes: "_"
          excludeSubdirectoriesWithPrefixes: "_"

        buildingModeDependent:
          LOCAL_DEVELOPMENT:
            outputTopDirectoryRelativePath: Workbenches/Output


  # ━━━ ECMAScript Logic Processing ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
  ECMA_ScriptLogicProcessing:

    entryPointsGroups:

      Distributable:

        singleEntryPointSourceFileRelativePath: Source/index.ts

        targetRuntime:
          type: BROWSER

        distributing:
          exposingOfExportsFromEntryPoints:
            mustExpose: true
          externalizingDependencies: [ @yamato-daiwa/frontend, react, react-dom, react-router-dom, next ]
          typeScriptTypesDeclarations:
            mustGenerate: true

        buildingModeDependent:

          LOCAL_DEVELOPMENT:
            outputTopDirectoryRelativePath: Distributable

          PRODUCTION:
            outputTopDirectoryRelativePath: Distributable
            revisioning: { disable: true }


      Workbenches:

        sourceFilesTopDirectoryRelativePath: Workbenches/Source

        partialsRecognition:
          excludeFilesWithPrefixes: "_"
          excludeSubdirectoriesWithPrefixes: "_"

        targetRuntime:
          type: BROWSER

        buildingModeDependent:
          LOCAL_DEVELOPMENT:
            outputTopDirectoryRelativePath: Workbenches/Output


  # ━━━ Development Server ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
  browserLiveReloading:

    setups:

      Workbenches:

        localServer:

          rootDirectoryRelativePath: Workbenches/Output
          customStartingFileNameWithExtension: Workbenches.html

        openInBrowsers: chrome


  # ━━━ Files Watching ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
  filesWatching:

    relativePathsOfExcludeDirectories:
      - Distributable
      - LocalDatabase
