fontsStacks:

  $heading: "<code>fontsStacks</code>"
  $anchor: FONTS_STACKS--SECTION

  $sectioning:

    mainSansSerif:
      $heading: "<code>mainSansSerif</code>"
      $anchor: FONT_STACKS-MAIN_SANS_SERIF--SECTION

    mainSerif:
      $heading: "<code>mainSerif</code>"
      $anchor: FONT_STACKS-MAIN_SERIF--SECTION

    mainMonospaced:
      $heading: "<code>mainMonospaced</code>"
      $anchor: FONT_STACKS-MAIN_MONOSPACED--SECTION

textGeometry:

  $heading: "<code>textGeometry</code>"
  $anchor: TEXT_GEOMETRY--SECTION

  $sectioning:

    basicFontSize:
      $heading: "<code>basicFontSize</code>"
      $anchor: TEXT_GEOMETRY-BASIC_FONT_SIZE--SECTION

    basicLineHeight:
      $heading: "<code>basicLineHeight</code>"
      $anchor: TEXT_GEOMETRY-BASIC_LINE_HEIGHT--SECTION

    basicLineHeightInMultilineTextBlocks:
      $heading: "<code>basicLineHeightInMultilineTextBlocks</code>"
      $anchor: TEXT_GEOMETRY-BASIC_LINE_HEIGHT_IN_MULTILINE_TEXT_BLOCKS--SECTION

zIndexes:
  $heading: "zIndexes"
  $anchor: Z_INDEXES--SECTION
