projectBuilding:

  commonSettings:

    selectiveExecutions:

      PugAuxiliaries:
        tasksAndSourceFilesSelection:
          ECMA_ScriptLogicProcessing: [ PugExtensions, ComponentsDefaultLocalizations ]

      Logic:
        tasksAndSourceFilesSelection:
          ECMA_ScriptLogicProcessing: [ Logic ]

      StylesAndComponentsTesting:

        tasksAndSourceFilesSelection:
          markupProcessing: [ StylesAndComponentsTesting ]
          stylesProcessing: [ StylesAndComponentsTesting ]
          ECMA_ScriptLogicProcessing: [ StylesAndComponentsTesting ]

        browserLiveReloadingSetupID: StylesAndComponentsTesting

      Workbenches:

        tasksAndSourceFilesSelection:
          markupProcessing: [ Workbenches ]
          stylesProcessing: [ Workbenches ]
          ECMA_ScriptLogicProcessing: [ Workbenches ]

        browserLiveReloadingSetupID: Workbenches

      StaticPreviewAnywherePage:
        tasksAndSourceFilesSelection:
          stylesProcessing: [ StaticPreviewAnywherePage ]


  # === Markup =========================================================================================================
  markupProcessing:

    common:

      buildingModeDependent:

        LOCAL_DEVELOPMENT:

          mustResolveResourceReferencesToRelativePaths: true

    entryPointsGroups:

      StylesAndComponentsTesting:
        sourceFilesTopDirectoryRelativePath: Tests/Source
        partialsRecognition:
          excludeFilesWithPrefixes: "_"
          excludeSubdirectoriesWithPrefixes: "_"
        buildingModeDependent:
          LOCAL_DEVELOPMENT:
            outputTopDirectoryRelativePath: Tests/Build

      Workbenches:
        sourceFilesTopDirectoryRelativePath: Workbenches/Source
        partialsRecognition:
          excludeFilesWithPrefixes: "_"
          excludeSubdirectoriesWithPrefixes: "_"
        buildingModeDependent:
          LOCAL_DEVELOPMENT:
            outputTopDirectoryRelativePath: Workbenches/Build


  # === Styles =========================================================================================================
  stylesProcessing:

    entryPointsGroups:

      StylesAndComponentsTesting:

        sourceFilesTopDirectoryRelativePath: Tests/Source

        partialsRecognition:
          excludeFilesWithPrefixes: "_"
          excludeSubdirectoriesWithPrefixes: "_"
          excludeSubdirectoriesWithNames: [ "CompiledCodeCheckOnly" ]

        buildingModeDependent:
          LOCAL_DEVELOPMENT:
            outputTopDirectoryRelativePath: Tests/Build

      Workbenches:

        sourceFilesTopDirectoryRelativePath: Workbenches/Source

        partialsRecognition:
          excludeFilesWithPrefixes: "_"
          excludeSubdirectoriesWithPrefixes: "_"

        buildingModeDependent:
          LOCAL_DEVELOPMENT:
            outputTopDirectoryRelativePath: Workbenches/Build

      OutputCheck:

        sourceFilesTopDirectoryRelativePath: Tests/Source/OutputCheckOnly

        buildingModeDependent:
          LOCAL_DEVELOPMENT:
            outputTopDirectoryRelativePath: Tests/Build/OutputCheck


      StaticPreviewAnywherePage:

        singleEntryPointSourceFileRelativePath: PagesTemplates/StaticPreviewAnywherePage/StaticPreviewAnywherePage.styl

        buildingModeDependent:
          LOCAL_DEVELOPMENT:
            outputTopDirectoryRelativePath: PagesTemplates/StaticPreviewAnywherePage


  # === ECMAScript logic processing ====================================================================================
  ECMA_ScriptLogicProcessing:

    entryPointsGroups:

      Logic:

        singleEntryPointSourceFileRelativePath: index.ts

        targetRuntime:
          type: BROWSER

        distributing:
          exposingOfExportsFromEntryPoints:
            mustExpose: true
          typeScriptTypesDeclarations:
            mustGenerate: true

        buildingModeDependent:

          PRODUCTION:
            outputTopDirectoryRelativePath: "LogicDistributable"
            revisioning: { disable: true }


      PugExtensions:

        singleEntryPointSourceFileRelativePath: Markup/InlineECMAScript/Source/PugExtensions.ts

        targetRuntime:
          type: PUG

        distributing:
          exposingOfExportsFromEntryPoints:
            mustExpose: true
            namespace: __PUG_EXTENSIONS_EXPORTS__

        buildingModeDependent:
          PRODUCTION:
            outputTopDirectoryRelativePath: Markup/InlineECMAScript/Temporary
            revisioning: { disable: true }


      ComponentsDefaultLocalizations:

        singleEntryPointSourceFileRelativePath: Markup/InlineECMAScript/Source/ComponentsDefaultLocalizations.ts

        targetRuntime:
          type: PUG

        distributing:
          exposingOfExportsFromEntryPoints:
            mustExpose: true
            namespace: __COMPONENTS_DEFAULT_LOCALIZATIONS_EXPORTS__

        buildingModeDependent:
          PRODUCTION:
            outputTopDirectoryRelativePath: Markup/InlineECMAScript/Temporary
            revisioning: { disable: true }

      StylesAndComponentsTesting:

        sourceFilesTopDirectoryRelativePath: Tests/Source

        targetRuntime:
          type: BROWSER

        partialsRecognition:
          excludeFilesWithPrefixes: "_"
          excludeSubdirectoriesWithPrefixes: "_"

        buildingModeDependent:
          LOCAL_DEVELOPMENT:
            outputTopDirectoryRelativePath: Tests/Build

      Workbenches:

        sourceFilesTopDirectoryRelativePath: Workbenches/Source

        targetRuntime:
          type: BROWSER

        partialsRecognition:
          excludeFilesWithPrefixes: "_"
          excludeSubdirectoriesWithPrefixes: "_"

        buildingModeDependent:
          LOCAL_DEVELOPMENT:
            outputTopDirectoryRelativePath: Workbenches/Build


  # === Development server =============================================================================================
  browserLiveReloading:

    setups:

      StylesAndComponentsTesting:

        localServer:

          rootDirectoryRelativePath: Tests/Build
          customStartingFileNameWithExtension: Tests.html

        openInBrowsers: chrome

      Workbenches:

        localServer:

          rootDirectoryRelativePath: Workbenches/Build
          customStartingFileNameWithExtension: Workbenches.html

        openInBrowsers: chrome
