projectBuilding:

  commonSettings:

    selectiveExecutions:

      Distributable:

        tasksAndSourceFilesSelection:

          ECMA_ScriptLogicProcessing: [ Distributable ]

      Tests:

        tasksAndSourceFilesSelection:

          markupProcessing: [ Tests ]
          stylesProcessing: [ Tests ]
          ECMA_ScriptLogicProcessing: [ Tests ]

        browserLiveReloadingSetupID: Tests


  # ━━━ Markup ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
  markupProcessing:

    common:
      buildingModeDependent:
        LOCAL_DEVELOPMENT: { mustResolveResourceReferencesToRelativePaths: true }

    entryPointsGroups:

      Tests:

        sourceFilesTopDirectoryRelativePath: Tests/Source
        partialsRecognition:
          excludeFilesWithPrefixes: "_"
          excludeSubdirectoriesWithPrefixes: "_"

        buildingModeDependent:
          LOCAL_DEVELOPMENT:
            outputTopDirectoryRelativePath: Tests/Output


  # ━━━ Styles ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
  stylesProcessing:

    entryPointsGroups:

      Tests:

        sourceFilesTopDirectoryRelativePath: Tests/Source

        partialsRecognition:
          excludeFilesWithPrefixes: "_"
          excludeSubdirectoriesWithPrefixes: "_"

        buildingModeDependent:
          LOCAL_DEVELOPMENT:
            outputTopDirectoryRelativePath: Tests/Output


  # ━━━ ECMAScript Logic Processing ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
  ECMA_ScriptLogicProcessing:

    entryPointsGroups:

      Distributable:

        singleEntryPointSourceFileRelativePath: Source/index.ts

        targetRuntime:
          type: BROWSER

        distributing:
          exposingOfExportsFromEntryPoints:
            mustExpose: true
          externalizingDependencies: [ @yamato-daiwa/frontend, react, react-dom, react-router-dom, next ]
          typeScriptTypesDeclarations:
            mustGenerate: true

        buildingModeDependent:

          LOCAL_DEVELOPMENT:
            outputTopDirectoryRelativePath: Distributable

          PRODUCTION:
            outputTopDirectoryRelativePath: Distributable
            revisioning: { disable: true }


      Tests:

        sourceFilesTopDirectoryRelativePath: Tests/Source

        partialsRecognition:
          excludeFilesWithPrefixes: "_"
          excludeSubdirectoriesWithPrefixes: "_"

        targetRuntime:
          type: BROWSER

        buildingModeDependent:
          LOCAL_DEVELOPMENT:
            outputTopDirectoryRelativePath: Tests/Output


  # ━━━ Development Server ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
  browserLiveReloading:

    setups:

      Tests:

        localServer:

          rootDirectoryRelativePath: Tests/Output
          customStartingFileNameWithExtension: Tests.html

        openInBrowsers: chrome


  # ━━━ Files Watching ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
  filesWatching:

    relativePathsOfExcludeDirectories:
      - Distributable
      - LocalDatabase
