projectBuilding:

  commonSettings:

    selectiveExecutions:

      LocalGalleries:

        tasksAndSourceFilesSelection:
          markupProcessing: [ LocalGalleriesIndexPage, CompletePages ]
          ECMA_ScriptLogicProcessing: [ CompletePages ]
          plainCopying: [ ExternalStyles ]

        browserLiveReloadingSetupID: LocalGalleries

      Distributions:

        tasksAndSourceFilesSelection:
          markupProcessing: [ CompletePages, PartialDemos ]
          ECMA_ScriptLogicProcessing: [ CompletePages ]
          plainCopying: [ ExternalStyles ]

      PartialDemosSourceFiles:

        tasksAndSourceFilesSelection:
          plainCopying: [ PartialDemos ]


  # ━━━ Markup ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
  markupProcessing:

    common:
      buildingModeDependent:
        LOCAL_DEVELOPMENT: { mustResolveResourceReferencesToRelativePaths: true }
        PRODUCTION: { mustResolveResourceReferencesToRelativePaths: true }

    entryPointsGroups:

      LocalGalleriesIndexPage:

        singleEntryPointSourceFileRelativePath: Source/LocalGalleriesIndexPage.pug
        buildingModeDependent:
          LOCAL_DEVELOPMENT: { outputTopDirectoryRelativePath: LocalGalleriesBuild }

      CompletePages:

        sourceFilesTopDirectoryRelativePath: Source/CompletePages

        partialsRecognition:
          excludeFilesWithPrefixes: "_"
          excludeSubdirectoriesWithPrefixes: "_"

        buildingModeDependent:
          LOCAL_DEVELOPMENT: { outputTopDirectoryRelativePath: LocalGalleriesBuild }
          PRODUCTION: { outputTopDirectoryRelativePath: Distributions }

      PartialDemos:

        sourceFilesTopDirectoryRelativePath: Source/PartialDemos

        partialsRecognition:
          excludeFilesWithPrefixes: "_"
          excludeSubdirectoriesWithPrefixes: "_"

        buildingModeDependent: { PRODUCTION: { outputTopDirectoryRelativePath: Distributions } }


  # ━━━ ECMAScript Logic Processing ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
  ECMA_ScriptLogicProcessing:

    entryPointsGroups:

      CompletePages:

        sourceFilesTopDirectoryRelativePath: Source/CompletePages

        partialsRecognition:
          excludeFilesWithPrefixes: "_"
          excludeSubdirectoriesWithPrefixes: "_"

        targetRuntime:
          type: BROWSER

        buildingModeDependent:
          LOCAL_DEVELOPMENT: { outputTopDirectoryRelativePath: LocalGalleriesBuild }
          PRODUCTION: { outputTopDirectoryRelativePath: Distributions }


  # ━━━ Plain copying ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
  plainCopying:

    filesGroups:

      ExternalStyles:
        sourceTopDirectoryRelativePath: node_modules/@yamato-daiwa/frontend-demos/Distributions
        fileNameLastExtensions: [ "css" ]
        buildingModeDependent:
          LOCAL_DEVELOPMENT:
            outputTopDirectoryRelativePath: LocalGalleriesBuild
          PRODUCTION:
            outputTopDirectoryRelativePath: Distributions/Demos
            outputDirectoryPathTransformations: { segmentsCountRelativeToGroupTopDirectoryWhichMustBeRemoved: 1 }

      PartialDemos:
        sourceTopDirectoryRelativePath: node_modules/@yamato-daiwa/frontend-demos/Source/PartialDemos
        buildingModeDependent:
          PRODUCTION: { outputTopDirectoryRelativePath: Source/PartialDemos }


  # ━━━ Browser Live Reloading ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
  browserLiveReloading:

    setups:

      LocalGalleries:

        localServer:

          rootDirectoryRelativePath: LocalGalleriesBuild
          customStartingFileNameWithExtension: LocalGalleriesIndexPage.html

        openInBrowsers: chrome


  # ━━━ Files Watching ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
  filesWatching:

    relativePathsOfExcludeDirectories:
      - Distributions
      - LocalGalleriesBuild
